/* Automatically generated by CMake */
/* Generated:  */

#ifndef COMPILER_DETAILS_H_INCLUDED
#define COMPILER_DETAILS_H_INCLUDED

/* Endianness detection for Maximus CBCS
 *
 * Defines exactly one of: MAXIMUS_BIG_ENDIAN or MAXIMUS_LITTLE_ENDIAN
 *
 * These prefixed macros avoid conflicts with system headers like <endian.h>
 * which often define LITTLE_ENDIAN and BIG_ENDIAN as numeric constants.
 */

#undef MAXIMUS_BIG_ENDIAN
#undef MAXIMUS_LITTLE_ENDIAN

/* CMake detection */
#define MAXIMUS_LITTLE_ENDIAN

/* Compile-time fallback using GCC builtins */
#if !defined(MAXIMUS_BIG_ENDIAN) && !defined(MAXIMUS_LITTLE_ENDIAN)
#if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__) && defined(__ORDER_BIG_ENDIAN__)
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
#define MAXIMUS_LITTLE_ENDIAN
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
#define MAXIMUS_BIG_ENDIAN
#endif
#endif
#endif

/* Validation */
#if defined(MAXIMUS_BIG_ENDIAN) && defined(MAXIMUS_LITTLE_ENDIAN)
#error MAXIMUS_BIG_ENDIAN and MAXIMUS_LITTLE_ENDIAN cannot both be defined!
#endif

#if !defined(MAXIMUS_BIG_ENDIAN) && !defined(MAXIMUS_LITTLE_ENDIAN)
#error Either MAXIMUS_BIG_ENDIAN or MAXIMUS_LITTLE_ENDIAN must be defined!
#endif

#endif /* COMPILER_DETAILS_H_INCLUDED */
