/* Automatically generated by configure */
/* Generated: Mon Nov 10 2025 */

#ifndef _COMPILER_DETAILS_H
#define _COMPILER_DETAILS_H
#undef BIG_ENDIAN
#undef LITTLE_ENDIAN
#define LITTLE_ENDIAN

#endif /* _COMPILER_DETAILS_H */
